// Code generated by "esc -o bindata/esc.go -pkg=bindata templates"; DO NOT EDIT.

package bindata

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/templates/call.tmpl": {
		name:    "call.tmpl",
		local:   "templates/call.tmpl",
		size:    246,
		modtime: 1737541642,
		compressed: `
H4sIAAAAAAAC/0SOQUrGQAyF954ilC4USg4geIBuRFR0HaZpDbSjZKIiIXeXGfr/s3rw5pv3xX3hVTLD
kGjfhwj3X7EPwGdOLD+stZEV8qcBzuXF9DtZhHExdOe81PcLCxjRW3ykgyNu3ZXyxjDKBCPvcP8A+ERK
BxtrOfdHiZjg+rcb31WsXtGMpFvpgjZSnY3H178vxrm8kQotkiIQO9vi7syb/wAAAP//LOB7BvYAAAA=
`,
	},

	"/templates/function.tmpl": {
		name:    "function.tmpl",
		local:   "templates/function.tmpl",
		size:    2679,
		modtime: 1737541713,
		compressed: `
H4sIAAAAAAAC/7RWTY/bNhA9y79iYmwCqXCY+y720CDbIofGhXfRHIKi4EojlyhNqSS1gUHwvxf80pcl
Jz3kYkkjzsybeW9GNqbCmgmEbd2JUrNGbK3dGPMWbmq4vQdi7WbjXoEx5AmV/kRPaG2u4SeNSjNxJE8F
mE3mXL4y/TeQA5bIXlBau8m8mdVAPqpHLbtSe2Nv/YUhr1SwZfrcItTeAsofdnHjaUnFEWcOmTH+2YH0
8M4txlfOBUUVn/qcyTS6n906VK7M36mkJ9QofTIPjcrjBNgI1qWHT+hNF+hGGaf5XUOVa7oxHodrdWXt
ibZflJZMHP8M2Y1BrtDaL8OzCxBBOddcNDr6F9YKekIIEeLRiGKBr9QEKqqBtFnfI0fh0rfWQ4qFp5CX
zKywcKX3WeYb734WfEYEHFB1XKuU5zMV+lrv+5QH1J0U6kHKJvbgKxX6QUp4bho+I8z1+N07eNp/2N/C
z1UFjjQoqUJFPJ91I8EYx0EjgTx2z4HVwMhH9Yn+g1VReFgjjh1Fida/Ikm7ENvrIRAcig0BzaiClGVS
lusi58itTWHc9W6qgMR0OjwB5Hzc9c4YVz94L00OnchXwbscJBpCEW55XK6LRZz9fV5MYfajvKbalT1z
oUXfTK+zc4v+MJXWvonZolLIH5R3aK1JIVbWT2YMCevw1veWhIkgo7W0G0IM6yhb2FEXDzHjwlZJhX6W
TPf1T7bN7T28eT5rVOR9V9cozfckjFIIQt0Lfh7PRXFp3wv0fSqgR6bx1HKqEbYyzOIWbmov9eFNSTkP
5jUUCwOZsTryNgdmLaCUgdelJHf98OTu3Kt7EIwX7uoZS5MeqdbEB63z7TjaCZWiR4zFoDsB9/D6ZQfJ
/fXLdjcBwETb9eWjlLtJumJQRdp5k+Xl340HG6yVvug0ZmUjNBMdDmPy7Y/e1X25qivf+V8bPYxPrzPy
6L8peXE3OpI6O17Ag/q4wpjlPVWsHH2xe4pv6iWVueGcoBj3mjOBc7r/B6IfhOCVxJpjqckHxPbh347y
vI+wm0Mqxph6Dr9HjwlyhPtbxzVr+QRuRDRo9huCvQJz/f/UTK/gSgpH4G34r2M3m6TX/wIAAP//jolB
r3cKAAA=
`,
	},

	"/templates/header.tmpl": {
		name:    "header.tmpl",
		local:   "templates/header.tmpl",
		size:    142,
		modtime: 1732193648,
		compressed: `
H4sIAAAAAAAC/0TMMQ7CMAyF4d2nsDrBQC7BxIK4gkUebYXiViGb9e6OlAi6/bL1voiM1+rQaYFl1ImU
iGo+Q9N1KwXePmRE6g941gspuz3fNkMj0mMkKbKWfatNT4dw65cB3K2AHJO2/DhSzv/6BgAA///GzMM9
jgAAAA==
`,
	},

	"/templates/inline.tmpl": {
		name:    "inline.tmpl",
		local:   "templates/inline.tmpl",
		size:    49,
		modtime: 1732193648,
		compressed: `
H4sIAAAAAAAC/6quTklNy8xLVVDKzMvJzEtVqq1VqK4uSc0tyEksSVVQSk7MyVFS0AOLpual1NYCAgAA
//+q60H/MQAAAA==
`,
	},

	"/templates/inputs.tmpl": {
		name:    "inputs.tmpl",
		local:   "templates/inputs.tmpl",
		size:    181,
		modtime: 1737541581,
		compressed: `
H4sIAAAAAAAC/0zNsQoDMQiA4b1PIceNxQco9AG6lEKfwHLmyBBb1JvEdy8JN2RK/JDfiI1LFYalyu9w
WzIj1gK3O2D/1gLydcD38XE2t9me1HjL7I4RLFumUOMrnMPYXAu+tIo/Rr6jkuw8nJQaO6udEdLdMGJ4
Pz+V5ufyDwAA///GSNEztQAAAA==
`,
	},

	"/templates/message.tmpl": {
		name:    "message.tmpl",
		local:   "templates/message.tmpl",
		size:    201,
		modtime: 1732193648,
		compressed: `
H4sIAAAAAAAC/zyN4WqDQBCE//sUiyi0oPsAhT5A/xRpS/9f4mgW9GLuTkNY9t2DB/HXDDPDN6o9BvGg
ckaMbkRJrVmhKgP5ayL+XU8JMUWz+sakCt+bqd4lXYh/cIZsCHvCf48F/O+mFWZ8DPnbzTB7y0Tugvj0
5Zd1B6oG50dQJQ1VmOjjk7hzwc1ICLmXgSoxa16/9XZws7wXqi1l+wwAAP//kC65UskAAAA=
`,
	},

	"/templates/results.tmpl": {
		name:    "results.tmpl",
		local:   "templates/results.tmpl",
		size:    168,
		modtime: 1732193648,
		compressed: `
H4sIAAAAAAAC/1yNTQrCQAyFr/Iosyw9gOBS3HsDoRkJlAy8ma5C7i6pRcFVfr4vee6rVDXBROn7NvoU
AXc+7SUoOqPIhssVy+ODI9y1omjEDHexNTf3NrBkc85a82DstH4jG1MW8uQ4hMbv0385A3/uUd8BAAD/
/7BPz2GoAAAA
`,
	},

	"/templates": {
		name:  "templates",
		local: `templates`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"templates": {
		_escData["/templates/call.tmpl"],
		_escData["/templates/function.tmpl"],
		_escData["/templates/header.tmpl"],
		_escData["/templates/inline.tmpl"],
		_escData["/templates/inputs.tmpl"],
		_escData["/templates/message.tmpl"],
		_escData["/templates/results.tmpl"],
	},
}
